---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-bench-cron-daily
  #namespace: kube-system
spec:
  schedule: "@daily"
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  jobTemplate:
    metadata:
      #namespace: kube-system
    spec:
      template:
        metadata:
          #namespace: kube-system
          labels:
            EksGatekeeper: ignore
        spec:
          hostPID: true
          containers:
            - name: kube-bench-daily
              # Push the image to your ECR and then refer to it here
              image: 758878116931.dkr.ecr.us-west-2.amazonaws.com/k8s/kube-bench:latest
              # image: aquasec/kube-bench:latest
              # To send findings to AWS Security Hub, refer to `job-eks-asff.yaml` instead
              command: ["kube-bench", "node", "--benchmark", "eks-1.0"]
              volumeMounts:
                - name: var-lib-kubelet
                  mountPath: /var/lib/kubelet
                  readOnly: true
                - name: etc-systemd
                  mountPath: /etc/systemd
                  readOnly: true
                - name: etc-kubernetes
                  mountPath: /etc/kubernetes
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: var-lib-kubelet
              hostPath:
                path: "/var/lib/kubelet"
            - name: etc-systemd
              hostPath:
                path: "/etc/systemd"
            - name: etc-kubernetes
              hostPath:
                path: "/etc/kubernetes"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-bench-cron-hourly
  #namespace: kube-system
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 23
  failedJobsHistoryLimit: 23
  jobTemplate:
    metadata:
      #namespace: kube-system
    spec:
      template:
        metadata:
          #namespace: kube-system
          labels:
            EksGatekeeper: ignore
        spec:
          hostPID: true
          containers:
            - name: kube-bench-hourly
              # Push the image to your ECR and then refer to it here
              image: 758878116931.dkr.ecr.us-west-2.amazonaws.com/k8s/kube-bench:latest
              # image: aquasec/kube-bench:latest
              # To send findings to AWS Security Hub, refer to `job-eks-asff.yaml` instead
              command: ["kube-bench", "node", "--benchmark", "eks-1.0"]
              volumeMounts:
                - name: var-lib-kubelet
                  mountPath: /var/lib/kubelet
                  readOnly: true
                - name: etc-systemd
                  mountPath: /etc/systemd
                  readOnly: true
                - name: etc-kubernetes
                  mountPath: /etc/kubernetes
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: var-lib-kubelet
              hostPath:
                path: "/var/lib/kubelet"
            - name: etc-systemd
              hostPath:
                path: "/etc/systemd"
            - name: etc-kubernetes
              hostPath:
                path: "/etc/kubernetes"
